# Generated by Django 5.1.2 on 2024-10-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="countryweather",
            name="date",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="countryweather",
            name="dew_point",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="countryweather",
            name="feels_like",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="countryweather",
            name="pressure",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="countryweather",
            name="temp_max",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="countryweather",
            name="temp_min",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="countryweather",
            name="time",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="countryweather",
            name="visibility",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="countryweather",
            name="weather_condition",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="countryweather",
            name="wind_speed",
            field=models.FloatField(null=True),
        ),
    ]
